from django.urls import path
from . import views

urlpatterns = [
    path('', views.profile_view, name='profile'),
    path('dashboard/', views.dashboard_view, name='dashboard'),
    path('price-lists/', views.price_list_list_view, name='price_list_list'),
    path('price-lists/<int:pk>/', views.price_list_detail_view, name='price_list_detail'),
    path('price-lists/<int:pk>/items/<int:item_pk>/edit/', views.price_list_item_edit_view, name='price_list_item_edit'),
    path('price-lists/create/', views.create_price_list_view, name='create_price_list'),
    path('price-lists/<int:pk>/delete/', views.delete_price_list_view, name='delete_price_list'),
    path('price-lists/<int:pk>/items/create/', views.create_price_list_item_view, name='create_price_list_item'),
    path('price-lists/<int:pk>/items/<int:item_pk>/update/', views.update_price_list_item_view, name='update_price_list_item'),
    path('price-lists/<int:pk>/items/<int:item_pk>/delete/', views.delete_price_list_item_view, name='delete_price_list_item'),
    path('price-lists/<int:pk>/items/<int:item_pk>/photos/create/', views.create_price_list_item_photo_view, name='create_price_list_item_photo'),
    path('price-lists/<int:pk>/items/<int:item_pk>/photos/<int:photo_pk>/main/', views.set_price_list_item_photo_main_view, name='set_price_list_item_photo_main'),
    path('price-lists/<int:pk>/items/<int:item_pk>/photos/<int:photo_pk>/delete/', views.delete_price_list_item_photo_view, name='delete_price_list_item_photo'),
    path('price-lists/<int:pk>/items/<int:item_pk>/materials/create/', views.save_price_list_item_material_view, name='create_price_list_item_material'),
    path('price-lists/<int:pk>/items/<int:item_pk>/materials/<int:material_pk>/update/', views.save_price_list_item_material_view, name='update_price_list_item_material'),
    path('price-lists/<int:pk>/items/<int:item_pk>/materials/<int:material_pk>/delete/', views.delete_price_list_item_material_view, name='delete_price_list_item_material'),
    path('price-lists/<int:pk>/items/<int:item_pk>/works/create/', views.save_price_list_item_work_view, name='create_price_list_item_work'),
    path('price-lists/<int:pk>/items/<int:item_pk>/works/<int:work_pk>/update/', views.save_price_list_item_work_view, name='update_price_list_item_work'),
    path('price-lists/<int:pk>/items/<int:item_pk>/works/<int:work_pk>/delete/', views.delete_price_list_item_work_view, name='delete_price_list_item_work'),
    path('price-lists/<int:pk>/items/<int:item_pk>/external-costs/create/', views.save_price_list_item_external_cost_view, name='create_price_list_item_external_cost'),
    path('price-lists/<int:pk>/items/<int:item_pk>/external-costs/<int:external_cost_pk>/update/', views.save_price_list_item_external_cost_view, name='update_price_list_item_external_cost'),
    path('price-lists/<int:pk>/items/<int:item_pk>/external-costs/<int:external_cost_pk>/delete/', views.delete_price_list_item_external_cost_view, name='delete_price_list_item_external_cost'),
    path('slips/create/', views.create_slip_view, name='create_slip'),
    path('slips/<int:pk>/edit/', views.edit_slip_view, name='edit_slip'),
    path('slips/<int:pk>/delete/', views.delete_slip_view, name='delete_slip'),
    path('slips/<int:pk>/download/', views.download_slip_view, name='download_slip'),
    path('recipients/', views.recipient_list_view, name='recipient_list'),
    path('recipients/add/', views.add_recipient_view, name='add_recipient'),
    path('recipients/<int:pk>/edit/', views.edit_recipient_view, name='edit_recipient'),
    path('recipients/<int:pk>/delete/', views.delete_recipient_view, name='delete_recipient'),
    path('custom-print/', views.custom_print_view, name='custom_print'),
]   
