# Generated by Django 5.0.1 on 2026-05-10 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creato il')),
            ],
            options={
                'verbose_name': 'Listino Prezzi',
                'verbose_name_plural': 'Listini Prezzi',
                'ordering': ['-created_at', 'name'],
            },
        ),
    ]
