# Generated by Django 5.0.1 on 2026-05-10 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('price_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='user_profile.pricelist', verbose_name='Listino Prezzi')),
            ],
            options={
                'verbose_name': 'Voce Listino',
                'verbose_name_plural': 'Voci Listino',
                'ordering': ['id'],
            },
        ),
    ]
