# Generated by Django 5.0.1 on 2026-05-10 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_pricelistitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceListItemExternalCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_type', models.CharField(choices=[('fixed', 'Fisso'), ('percentage', 'Percentuale')], default='fixed', max_length=20, verbose_name='Tipo costo')),
                ('description', models.CharField(max_length=255, verbose_name='Descrizione')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valore')),
                ('applies_to', models.CharField(choices=[('materials', 'Materiali'), ('works', 'Lavorazioni'), ('subtotal', 'Subtotale'), ('subtotal_plus_fixed', 'Subtotale + costi fissi')], default='subtotal', max_length=30, verbose_name='Applica a')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Ordine')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Note')),
            ],
            options={
                'verbose_name': 'Costo Esterno',
                'verbose_name_plural': 'Costi Esterni',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PriceListItemMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_type', models.CharField(choices=[('yarn', 'Filato'), ('button', 'Bottone'), ('accessory', 'Accessorio'), ('label', 'Etichetta'), ('other', 'Altro')], default='yarn', max_length=20, verbose_name='Tipo materiale')),
                ('description', models.CharField(max_length=255, verbose_name='Descrizione')),
                ('supplier', models.CharField(blank=True, default='', max_length=255, verbose_name='Fornitore')),
                ('unit', models.CharField(blank=True, default='pz', max_length=20, verbose_name='Unita')),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Quantita')),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Costo unitario')),
                ('waste_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Sfrido %')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Ordine')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Note')),
            ],
            options={
                'verbose_name': 'Materiale Primario',
                'verbose_name_plural': 'Materiali Primari',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PriceListItemPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_image', models.ImageField(upload_to='price_list_items/')),
                ('is_main', models.BooleanField(default=False, verbose_name='Principale')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordine')),
            ],
            options={
                'verbose_name': 'Foto Capo Listino',
                'verbose_name_plural': 'Foto Capi Listino',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PriceListItemWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_name', models.CharField(max_length=255, verbose_name='Lavorazione')),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Quantita')),
                ('unit', models.CharField(blank=True, default='pz', max_length=20, verbose_name='Unita')),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Costo unitario')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Ordine')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Note')),
            ],
            options={
                'verbose_name': 'Lavorazione',
                'verbose_name_plural': 'Lavorazioni',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AlterModelOptions(
            name='pricelistitem',
            options={'ordering': ['sort_order', 'id'], 'verbose_name': 'Capo Listino', 'verbose_name_plural': 'Capi Listino'},
        ),
        migrations.AddField(
            model_name='pricelistitem',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descrizione'),
        ),
        migrations.AddField(
            model_name='pricelistitem',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Attivo'),
        ),
        migrations.AddField(
            model_name='pricelistitem',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Note'),
        ),
        migrations.AddField(
            model_name='pricelistitem',
            name='sku',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Codice / SKU'),
        ),
        migrations.AddField(
            model_name='pricelistitem',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Ordine'),
        ),
        migrations.AddConstraint(
            model_name='pricelistitem',
            constraint=models.UniqueConstraint(condition=models.Q(('sku', ''), _negated=True), fields=('price_list', 'sku'), name='unique_pricelistitem_sku_per_list_when_present'),
        ),
        migrations.AddField(
            model_name='pricelistitemexternalcost',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_costs', to='user_profile.pricelistitem', verbose_name='Capo Listino'),
        ),
        migrations.AddField(
            model_name='pricelistitemmaterial',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='user_profile.pricelistitem', verbose_name='Capo Listino'),
        ),
        migrations.AddField(
            model_name='pricelistitemphoto',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='user_profile.pricelistitem', verbose_name='Capo Listino'),
        ),
        migrations.AddField(
            model_name='pricelistitemwork',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works', to='user_profile.pricelistitem', verbose_name='Capo Listino'),
        ),
    ]
