# Generated by Django 5.0.1 on 2026-05-10 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_pricelistitemexternalcost_pricelistitemmaterial_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='pricelistitem',
            name='unique_pricelistitem_sku_per_list_when_present',
        ),
    ]
