# Generated by Django 5.0.1 on 2026-05-12 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_remove_pricelistitem_unique_pricelistitem_sku_per_list_when_present'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricelistitemmaterial',
            name='unit_cost',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='Costo unitario'),
        ),
        migrations.AlterField(
            model_name='pricelistitemwork',
            name='unit_cost',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='Costo unitario'),
        ),
    ]
